name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create an order with...
        2. Submit to matching engine...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Reproducible Example
      description: If possible, provide a minimal code example that reproduces the issue.
      render: rust
      placeholder: |
        use matching_engine::*;

        fn main() {
            // Code that reproduces the bug
        }

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of matching-engine are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: rust-version
    attributes:
      label: Rust Version
      description: What Rust version are you using?
      options:
        - stable (latest)
        - beta
        - nightly
        - "1.83.0"
        - "1.80.0"
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.).
