name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Suggested API
      description: If applicable, show how the API might look.
      render: rust
      placeholder: |
        // Example of how you'd like to use this feature
        let engine = MatchingEngine::new()
            .with_new_feature(config);

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: List any workarounds or alternative approaches...

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
